Traceback (most recent call last):
  File "upload_s3.py", line 78, in <module>
    os.remove(os.path.join(local_logs_path, log_file))
OSError: [Errno 21] Is a directory: '/var/opt/tableau/tableau_server/data/tabsvc/logs/databasemaintenance/34d53bb2'
